### ISSUE TITLE
BPR learning example

### ISSUE THREAD

**Issue by parklize** [RankSys/JavaFM#1]
Hi @saulvargas, 

Thanks for the great implementation of FM using Java8.

I tried to use BPR-FM, and have some confusion about the implementation. Based on my understanding, sij() should be the pairwise comparison, and then uij() should contain user-index, item1-index, and item2-index. 

    // pairwise comparison
    private static double sij(FM fm, int[] uij) {
        FMInstance xi = new FMInstance(NaN, new int[]{uij[0], uij[1]}, new double[]{1.0, 1.0});
        FMInstance xj = new FMInstance(NaN, new int[]{uij[0], uij[2]}, new double[]{1.0, 1.0});

        return fm.predict(xi) - fm.predict(xj);
    }

However, uij() does not seem to do that based on normal FMInstance with [user, item, feedback/rating].

    private static int[] uij(FMInstance x) {
        int[] uij = new int[3];
        x.consume((i, xi) -> {
            uij[(int) xi - 1] = i;
        });

        return uij;
    }

Am I missing something here? or could you provide me an example with ML100kRatingRankingExample? 

Thank you.

**Comment by saulvargas** [comment]
Hi @parklize 

First of all, my apologies for answering so late, I messes my mail filters and did not get any notifications from Github for a long time. I understand this may be too late, but here is my answer.

The current implementation of BPR-FM is quite hackish, and it only covers a pure collaborative filtering scenario (no context, no user or item-side information). Please take a look at RankSys, in particular the code here https://github.com/RankSys/RankSys/blob/master/RankSys-fm/src/main/java/org/ranksys/fm/data/BPRPreferenceFMData.java and here https://github.com/RankSys/RankSys/blob/master/RankSys-examples/src/main/java/es/uam/eps/ir/ranksys/examples/RecommenderExample.java to know how I am actually using it.
